// =============================================================================
// Soci V2 — Listas fixas predefinidas
// Usadas em: onboarding, editar perfil, buscar, filtros
// =============================================================================

export const AREAS_INTERESSE = [
  "Tecnologia",
  "Design",
  "Marketing",
  "Vendas",
  "Financas",
  "RH",
  "Operacoes",
  "Engenharia",
  "Educacao",
  "Saude",
  "Direito",
  "Comunicacao",
  "Logistica",
  "Sustentabilidade",
  "Inovacao",
  "Empreendedorismo",
  "Consultoria",
  "Agronegocio",
  "Industria",
  "Varejo",
  "Construcao Civil",
  "Energia",
  "Alimentacao",
  "Moda",
  "Esportes",
  "Cultura",
  "Turismo",
  "Imobiliario",
  "Seguros",
  "Telecomunicacoes",
] as const;

export const AREAS_ATUACAO = [
  "Desenvolvimento Web",
  "Desenvolvimento Mobile",
  "UI/UX Design",
  "Design System",
  "Data Science",
  "Machine Learning",
  "DevOps",
  "Cloud Computing",
  "Ciberseguranca",
  "Gestao de Projetos",
  "Product Management",
  "Marketing Digital",
  "Growth",
  "SEO/SEM",
  "Copywriting",
  "Fotografia",
  "Video",
  "Consultoria Empresarial",
  "Consultoria Financeira",
  "Contabilidade",
  "Gestao de Pessoas",
  "Recrutamento",
  "Treinamento",
  "Vendas B2B",
  "Vendas B2C",
  "E-commerce",
  "Business Intelligence",
  "Automacao",
  "Arquitetura de Software",
  "QA/Testes",
] as const;

export const OBJETIVOS_LABELS: Record<string, string> = {
  oportunidades: "Oportunidades de trabalho",
  contratar: "Contratar colaboradores",
  conexoes: "Fazer novas conexoes",
} as const;

export const ESCOLARIDADE_OPTIONS = [
  { value: "ensino_fundamental_incompleto", label: "Ensino Fundamental Incompleto" },
  { value: "ensino_fundamental_completo", label: "Ensino Fundamental Completo" },
  { value: "ensino_medio_incompleto", label: "Ensino Medio Incompleto" },
  { value: "ensino_medio_completo", label: "Ensino Medio Completo" },
  { value: "ensino_tecnico_incompleto", label: "Ensino Tecnico Incompleto" },
  { value: "ensino_tecnico_completo", label: "Ensino Tecnico Completo" },
  { value: "ensino_superior_incompleto", label: "Ensino Superior Incompleto" },
  { value: "ensino_superior_completo", label: "Ensino Superior Completo" },
  { value: "pos_graduacao_incompleta", label: "Pos-graduacao Incompleta" },
  { value: "pos_graduacao_completa", label: "Pos-graduacao Completa" },
  { value: "mestrado_incompleto", label: "Mestrado Incompleto" },
  { value: "mestrado_completo", label: "Mestrado Completo" },
  { value: "doutorado_incompleto", label: "Doutorado Incompleto" },
  { value: "doutorado_completo", label: "Doutorado Completo" },
] as const;
